##  A function to take two continuous and one-two "level" predictors, and return a nice set of contour plots, from a glm() model object.
##
##
##
##  BLN, 23 Aug 2017
########################################################################33
##
##  Depends: lattice, latticeExtra
##
##
##  cplot (mod, focal.preds, focal.nms, cond.preds, cond.nms, quants = c(0.1, 0.5, 0.9), plot.title, file.nm)
##
##
##  Description:
## --------------
##  cplot() makes pretty contour plots using two "focal predictors, across levels of one or two "conditioning predictors."  It takes as input a model object with glm() (it could easily be altered to accommodate any object class that has a predict() method).  The model needs to have at least two continous predictors, and one or more predictors across whose "levels" you'd like to produce separate contour plots.  These levels could be 1) true factor levels, 2) the two values of a 0/1 binary variable, or 3) quantiles of a continuous predictor.
##  The set of plots is saved to a PNG file **in the present working directory** (so be sure to set this with setwd() first!). 
##
##  Arguments:
##---------------
##  mod          -- A model object generated by glm().
##  
##  focal.preds  -- A character vector of length 2, giving the names of the continuous predictors you want to use to generate each contour plot.  Names must match those used for the predictors in the model object!
##
##  focal.nms    -- A character vector of length 2, giving nice-looking names for the focal predictors, to appear in the plots.
##
##  cond.preds   -- A character vector of length 1 or 2, giving the names of the "conditioning predictors" across whose levels you want to look.  Names must match those used for the predictors in the model object!
##
##  cond.nms     -- A character vector, giving nice-looking names for the conditioning predictors, to appear in the plots.
##
##  quants       -- Vector of quantiles, for use in selecting values of continuous conditioning predictor(s).
##
##  plot.title   -- Title to print on the plot.
##
##  file.nm      -- Basename for the output PNG file.  If empty, inherits the value of plot.title. 
##
##  png.res      -- Resolution of the output PNG file.
##
##  inch         -- Base image size in inches.  This value is multiplied by the number of rows and columns in the plot, respectively, to determine the size of the image.
##
##  add.letters  -- Optionally add capital letters to each panel of the plot.
##
##
##
##  Example:
##---------------
##  gt <- read.csv('/your/path/to/burrows_pseudoabs_02jun2017.csv', stringsAsFactors=F)[1:9444,]
##  gt$gt <- ifelse(gt$type == "burrow", 1, 0)
##  gt$pndfld <- ifelse(gt$pondfreqcl == "None" & gt$flodfreqcl == "None", 0, 1)
##  mod <- glm(gt ~ sandtotal_r*new_suit + I(new_suit^2) + e_utm17 + pndfld, family="binomial", data = gt)
##  setwd("/your/path/to/images")
##  cplot(mod=mod,
##        focal.preds=c("e_utm17", "new_suit"),
##        focal.nms=c("Easting", "Soil suitability"),
##        cond.preds=c("sandtotal_r", "pndfld"),
##        cond.nms=c("% sand", "Ponding / Flooding"),
##        plot.title="",
##        file.nm="test", add.letters=T) 
##
##
##  Function Definition:
##------------------------


cplot.intxn <- function(mod, intxns, intxn.nms, sub = NULL, plot.title, file.nm = NULL, png.res=300, inch=4, pred.len = 100) {

  stopifnot("glm" %in% class(mod))
 
  require(lattice)
  require(latticeExtra)
  require(gridExtra)
  require(ggplot2)
  
  if (is.null(file.nm)) { file.nm <- plot.title } 

  response <- mod$terms[[2]]  
  cf <- coef(mod)

##  continuous predictors:
  trms <- attributes(terms(mod))$term.labels
  if (intxns == "all") {
    intxns <- intxn.nms <- sort(grep(trms, pattern = ":", fixed = T, value = T))
#    if (is.null(intxn.nms)) {
#      intxn.nms <- intxns    
#    }
  }  
  
  pair.lst <- strsplit(intxns, split = ":")
  nms.lst <- strsplit(intxn.nms, split = ":")
  names(pair.lst) <- names(nms.lst) <- intxns

  clss.get.s <- function (s) {
    attributes(terms(mod))$dataClasses[names(attributes(terms(mod))$dataClasses) == s]
  }
  clss.get.v <- function (v) {
    sapply(v, FUN = clss.get.s)
  }
  clss.lst <- lapply(pair.lst, FUN = clss.get.v)

  stopifnot(!all(unlist(clss.lst) == "factor"))

#####  STUFF FOR PLOTTING   ####################
rmp1 <- c("grey30", "lemonchiffon")
rmp2 <- c("grey30", "lightgreen")
cr <- colorRamp(colors = rmp1)

cr(seq(0,1,by = 0.01))/255 -> ramp
cols <- rgb(ramp[,1], ramp[,2], ramp[,3])
################################################

#row.col <- c(ceiling(length(clss.lst)/2), 2)   #### I'm not sure why I put a "2" here, originally....
row.col <- c(ceiling(length(clss.lst)/2), 1)
    


  intrxn.fun <- function(v, v.nms) {
     focal.vars <- mod$model[,match(v, names(mod$model))]
     focal.rng <- lapply(focal.vars, FUN = range)
     focal.mn <- sapply(focal.vars, FUN = mean)

     seq.fun <- function(v) {
       seq(from=v[1], to=v[2], length.out=pred.len)
     }
  
    focal.pre <- as.data.frame(lapply(focal.rng, FUN=seq.fun))
    focal.vals <- cbind(rep(focal.pre[,1], each=pred.len), rep(focal.pre[,2], times=pred.len))


  response <- mod$terms[[2]]  
  cf <- coef(mod)
  main <- names(cf)[names(cf) != "(Intercept)" & !grepl(x=names(cf), pattern="I\\(.*\\^2\\)") & !grepl(x=names(cf), pattern=".*:.*")]
  other.main <- main[!main %in% v]

  mn <- c()
  if (length(other.main) > 0) {
    mn <- numeric()
    for (i in 1:length(other.main)) {
      mn[i] <- mean(mod$model[,other.main[i]])
      names(mn)[i] <- other.main[i] 
    }
    pred.df <- as.data.frame(cbind(focal.vals, as.data.frame(matrix(mn, nrow = 1, byrow = T))))
  } else {
  pred.df <- as.data.frame(focal.vals)
  }
  
#  pred.df <- as.data.frame(cbind(focal.vals, as.data.frame(matrix(mn, nrow = 1, byrow = T))))
  names(pred.df) <- c(v, other.main)

  pred.vals <- round(predict(mod, newdata=pred.df, type="response"),6)
 
  pred <- cbind(pred.vals, pred.df)
  
  form <- paste("pred.vals ~", paste(v, collapse = " * "))     

  if (!exists("v.nms")) {
    v.nms <- gsub(v, pattern = "([0-9]{1,2})", replace = "[\\1]")
  } else {
    v.nms <- gsub(v.nms, pattern = "([0-9]{1,2})", replace = "[\\1]")
  }
     
  if (!is.null(sub)) {
    for (i in 1:length(sub)) {
      v.nms <- gsub(v.nms, pattern = sub[[i]][1], replace = sub[[i]][2], fixed = T)
      v.nms <- gsub(v.nms, pattern = " ", replace = "~", fixed = T)
    }
  }
    
    cp.pre <- contourplot(formula(form),
#            groups=grp,
            data = pred,
            subscripts = T,
            panel = function (x, y, z, fm = focal.mn,
                              subscripts = subscripts, 
                              clr = cols, ctr = seq(0,1,0.1)) {
                       panel.levelplot(x = x, y = y, z = z, subscripts = subscripts,
                          contour = F,
                          labels = F,
                          region = T,
                          at = ctr,
                          col.regions = clr)
                       panel.abline(v = fm[1], col = "red", subscripts = subscripts)
                       panel.abline(h = fm[2], col = "red", subscripts = subscripts)
                       panel.levelplot(x = x, y = y, z = z, subscripts = subscripts,
                          contour = T,
                          labels = T,
                          region = F,
                          at = ctr)
                    },
            aspect=1, 
            colorkey=FALSE,
            xlim=focal.rng[[1]],
            ylim=focal.rng[[2]],
            xlab=list(label=parse(text=v.nms[1])),
            ylab=list(label=parse(text=v.nms[2])))

#####  Try to add red lines, representing the means of each variable!

}

#cp.lst <- lapply(pair.lst, FUN = intrxn.fun)
cp.lst <- mapply(pair.lst, nms.lst, FUN = intrxn.fun, SIMPLIFY = FALSE)

  whole.nm <- paste(file.nm, "_", Sys.Date(), ".png", sep = "") 
  
#  png(file = whole.nm,
#      height = inch*row.col[1],
#      width = inch*row.col[2],
#      units = "in",
#      res = png.res)

g <- marrangeGrob(grobs = cp.lst, nrow = row.col[1], ncol = row.col[2], top = plot.title)

ggsave(filename = whole.nm, 
       plot = g,
       device = "png",
       height = inch*row.col[1],
       width = inch*row.col[2],
       units = "in",
       dpi = png.res)
       
#  dev.off()

  return(whole.nm)
  
}
  

